//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Wyam")]
[assembly: AssemblyVersion("0.11.0")]
[assembly: AssemblyFileVersion("0.11.0")]
[assembly: AssemblyInformationalVersion("0.11.0-beta")]
[assembly: AssemblyCopyright("Copyright (c) Wyam Contributors")]

