//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Wyam")]
[assembly: AssemblyVersion("0.12.2")]
[assembly: AssemblyFileVersion("0.12.2")]
[assembly: AssemblyInformationalVersion("0.12.2-beta")]
[assembly: AssemblyCopyright("Copyright © Wyam Contributors")]

